#! /bin/bash

token=`cat /var/lib/rancher/k3s/server/token`
clustername=`cat /etc/rancher/k3s/clustername`
for i in $(hostname -i)
do
  if [[ $i != 127* ]]
  then
    ip=$i
  fi
done

echo -e "\nInsert the following content to local file ~/.kube/config:\n### >>>"
sed "s/default/$clustername/g" /etc/rancher/k3s/k3s.yaml  | sed "s/127.0.0.1/$ip/g"
echo "### <<<"
echo
echo
echo "Execute on other nodes:"
echo "  curl -sfL https://get.k3s.io | K3S_TOKEN=$token sh -s - server --server https://$ip:6443"
echo
echo
echo "IP:    $ip"
echo "Token: $token"
echo
